### PR TITLE
Potential fix for reCaptcha problem

### PR DESCRIPTION
**Pull request by Kanishka-Chandra**
The code will now open a new instance of the browser for every upload/sales of a NFT. This is slower, but is a great fix for the time being.

### CODE REVIEW

**Comment by maximedrn** [comment]
Hi, thanks for your work! Are you sure it works every time or will the reCAPTCHAs be constantly present after a few restarts of the webdriver?

**Comment by maximedrn** [comment]
I'll do some research before I make a sweater request. I think it's possible to disconnect from OpenSea after each upload and clear the webdriver cache to start the task again, this will save much more time than relaunching the whole webdriver + connecting to the wallet.

However I will propose this solution in the open issue until I find if what I propose is possible.

**Comment by Kanishka-Chandra** [comment]
As far as I have tested it, it works. But after around 100 NFTs there is a reCaptcha which need to be manually completed, nevertheless. :(

PS. I am also a programmer like you and like to contribute to open-source, so need to thank me :)

**Comment by Kanishka-Chandra** [comment]
> I'll do some research before I make a sweater request. I think it's possible to disconnect from OpenSea after each upload and clear the webdriver cache to start the task again, this will save much more time than relaunching the whole webdriver + connecting to the wallet.
> 
> However I will propose this solution in the open issue until I find if what I propose is possible.

Sure if this can be done it will no way be better and faster. Especially because my tests so far show a substantial reduction in upload speeds using this method.

**Comment by maximedrn** [comment]
I am merging the pull request (to add you as a contributor and to thank you) but I will modify the code to make sure that when the connection to MetaMask/OpenSea fails, the bot restarts.
My bot loops on the connection if it fails so I had to add a counter to stop the webdriver after a certain number of failures.

**Comment by Kanishka-Chandra** [comment]
> I am merging the pull request (to add you as a contributor and to thank you) but I will modify the code to make sure that when the connection to MetaMask/OpenSea fails, the bot restarts. My bot loops on the connection if it fails so I had to add a counter to stop the webdriver after a certain number of failures.

That's great, hope this code help many more.😊

And, to be honest I should be the one thanking you in the first place to write this code and give me a starting point.

**Pull request merged**
